# Generated by Django 3.0.2 on 2020-01-15 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=50)),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generate_report.Batch')),
            ],
        ),
    ]
